import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { checkinFor, dueItems, hub, progress, recordCheckin, type Status } from "../domain.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
registerMainMenuItem({ label: "Check in", data: "check_in:start", order: 40 });
const composer = new Composer<Ctx>();
const statusLabel: Record<Status, string> = { done: "Done", skipped: "Skipped", missed: "Missed", progress: "In progress" };
function checkinKeyboard(ctx: Ctx) { const data = hub(ctx); const rows = dueItems(data).flatMap((item) => [[inlineButton(item.title, "noop")], [inlineButton("Done", `check:${item.id}:done`), inlineButton("In progress", `check:${item.id}:progress`)], [inlineButton("Skipped", `check:${item.id}:skipped`), inlineButton("Missed", `check:${item.id}:missed`)]]); rows.push([inlineButton("Back to dashboard", "dashboard:show")]); return inlineKeyboard(rows); }
function checkinText(ctx: Ctx): string { const data = hub(ctx); const due = dueItems(data); if (!due.length) return "No targets or habits are due today — create one when you’re ready."; return `Mark today’s steps in one tap.\n${due.map((i) => `${i.title}: ${checkinFor(data, i.id)?.status ? statusLabel[checkinFor(data, i.id)!.status] : "Not checked in"}`).join("\n")}`; }
composer.callbackQuery("check_in:start", async (ctx) => { await ctx.answerCallbackQuery(); await ctx.reply(checkinText(ctx), { reply_markup: checkinKeyboard(ctx) }); });
composer.callbackQuery("noop", async (ctx) => { await ctx.answerCallbackQuery(); });
composer.callbackQuery(/^check:([th]-\d+|t-revision):(done|skipped|missed|progress)$/, async (ctx) => { await ctx.answerCallbackQuery(); const data = hub(ctx); const item = data.items.find((i) => i.id === ctx.match[1]); if (!item || !item.active) { await ctx.reply("That item is no longer active. Your history is safely kept."); return; } const status = ctx.match[2] as Status; recordCheckin(data, item.id, status); const streak = data.streak.current; let message = status === "done" ? `Nice work — ${item.title} is done. Your streak is ${streak} days.` : status === "missed" ? "Today didn’t go to plan. One gentle restart tomorrow is enough." : status === "skipped" ? "Skipped is recorded. You can return to this tomorrow." : "Good start — keep going when you’re ready."; const milestones = [7, 30, 50, 100, 365]; if (status === "done" && milestones.includes(streak) && !data.streak.milestones.includes(streak)) { data.streak.milestones.push(streak); message = `Amazing — you reached a ${streak}-day streak. Keep trusting your routine.`; } await ctx.reply(message, { reply_markup: checkinKeyboard(ctx) }); });
composer.callbackQuery("weekly_report:generate", async (ctx) => { await ctx.answerCallbackQuery(); const data = hub(ctx); const week = progress(data, 7); const suggestion = week.total === 0 ? "Start with one small daily target this week." : week.missed > week.done ? "Make tomorrow’s target smaller and easier to begin." : "You’re building consistency — protect your next study block."; await ctx.reply(`Your weekly report\nCompleted: ${week.done}\nMissed: ${week.missed}\nStudy time: ${Math.floor(week.minutes / 60)}h ${week.minutes % 60}m\nStreak: ${data.streak.current} days\n${suggestion}`); });
composer.callbackQuery("items:manage", async (ctx) => { await ctx.answerCallbackQuery(); const data = hub(ctx); if (!data.items.some((i) => i.active)) { await ctx.reply("No active items yet — create a target or habit when you’re ready."); return; } await ctx.reply("Choose an item to archive. Your check-in history stays private and safe.", { reply_markup: inlineKeyboard(data.items.filter((i) => i.active).map((i) => [inlineButton(`Archive ${i.title}`, `archive:${i.id}`)])) }); });
composer.callbackQuery(/^archive:([th]-\d+|t-revision)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = hub(ctx).items.find((i) => i.id === ctx.match[1]); if (!item) return; await ctx.reply(`Archive ${item.title}? Your history will stay private and safe.`, { reply_markup: inlineKeyboard([[inlineButton("Archive item", `archive:yes:${item.id}`), inlineButton("Keep item", "items:manage")]]) }); });
composer.callbackQuery(/^archive:yes:([th]-\d+|t-revision)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = hub(ctx).items.find((i) => i.id === ctx.match[1]); if (!item) return; item.active = false; await ctx.reply(`${item.title} is archived. Your past progress is still counted.`); });
export default composer;
